---
- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  become: no
  vars:
    brew_packages:
      # git
      - git
      - git-lfs
      - git-secrets
      - tig
      - gh
      # infra
      - ansible
      - awscli
      - packer
      # lang
      - nodenv
      - goenv
      - pyenv
      - tfenv
      # others
      - direnv
      - docker-compose
      - fzf
      - jq
      - openssl
      - peco
      - tree
      - vim
      - wget

    brew_cask_apps:
      # browser
      - firefox
      - chromium
      - google-chrome
      # JetBrains
      - goland
      - pycharm
      - webstorm
      - android-studio
      # work
      - slack
      - sneek
      # others
      - docker
      - iTerm2
      - karabiner-elements
      - meld
      - skitch
      - 1Password

  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_cask_apps }}"

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
