---
- name: Mac Setup
  hosts: 127.0.0.1
  connection: local
  become: no
  vars:
    brew_packages:
      - byobu
      - docker-compose
      - git
      - git-lfs
      - openssl
      - tree
      - wget

    brew_cask_apps:
      # container
      - docker
      # browser
      - firefox
      - chromium
      - google-chrome
      # JetBrains
      - goland
      - pycharm
      - webstorm
      - android-studio
      # diff
      - meld
      # chat
      - slack

  tasks:
    - name: Update Homebrew
      homebrew:
        update_homebrew: yes

    - name: Install Homebrew Cask Packages
      homebrew_cask:
        name: "{{ item }}"
        state: "present"
      with_items: "{{ brew_cask_apps }}"

    - name: Install Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
        state: "present"
